### ISSUE TITLE
Improve examples for SealedBox and EasyBox

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Salt#12]
Libsodium has some documentation and some examples.

https://libsodium.gitbook.io/doc/

and

https://github.com/jedisct1/libsodium

Please add;

- document how to the same thing as some of the examples in Java.
- show a predefined message can be successfully encrypted.
- add a way to use a seed for the private/secret key for EasyBox.
- ensure the terminology for secret vs private is correct.

**Comment by rogersimmons** [comment]
EasyBox, SealedBox, and SHA-2 APIs extended
Signature API added (for message signing/verification)
Multi-part/multi-message support added for SHA-2 and Signatures
Seeding support added for EasyBox keys and Nonces, and Signature keys
Multiple test cases added covering the above (and using seeding for deterministic message encryption)
Documentation (README.adoc) updated with details and examples

**Comment by hft-team-city** [comment]
Released in [Chronicle-Salt-2.17.2](https://github.com/OpenHFT/Chronicle-Salt/releases/chronicle-salt-2.17.2), [BOM-2.17.119](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.119)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Salt-2.17.2](https://github.com/OpenHFT/Chronicle-Salt/releases/chronicle-salt-2.17.2), [BOM-2.17.196](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.196)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Salt-2.17.2](https://github.com/OpenHFT/Chronicle-Salt/releases/chronicle-salt-2.17.2), [BOM-2.17.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Salt-2.17.2](https://github.com/OpenHFT/Chronicle-Salt/releases/chronicle-salt-2.17.2), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)
