### ISSUE TITLE
Fix net.openhft.chronicle.salt.EasyBoxTest

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Salt#13]
please fix this test, net.openhft.chronicle.salt.EasyBoxTest, for now, it has been ignored because it fails on TeamCity, see http://teamcity.higherfrequencytrading.com/viewLog.html?buildId=309860&buildTypeId=OpenHFT_ChronicleSalt_Snapshot&tab=buildLog&_focus=14105

**Comment by RobAustin** [comment]
![pastedgraphic-2](https://user-images.githubusercontent.com/6506056/49513978-89732480-f88a-11e8-90d3-5f87967d4f03.png)

updated EasyBox to use sodium 1.0.16 but this test is still failing

**Comment by rogersimmons** [comment]
Confirmed. Amending the Java code to wrap all the addresses into a long[] array, and just forwarding this one argument via JNR FFI through an intermediate C .so which unpacks and calls on to sodium works fine (EasyBox tests pass). Using this as a stopgap for now while a fix from JNR FFI is pending.

**Comment by rogersimmons** [comment]
This is now fixed.
The 2 problematic EasyBox calls which are being corrupted by JNR-FFI has been switched to JNI for now following the same model as Chronicle-Ticker

**Comment by rogersimmons** [comment]
JNR-FFI issue raised:
https://github.com/jnr/jnr-ffi/issues/181

**Comment by hft-team-city** [comment]
Released in [Chronicle-Salt-2.17.2](https://github.com/OpenHFT/Chronicle-Salt/releases/chronicle-salt-2.17.2), [BOM-2.17.119](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.119)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Salt-2.17.2](https://github.com/OpenHFT/Chronicle-Salt/releases/chronicle-salt-2.17.2), [BOM-2.17.196](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.196)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Salt-2.17.2](https://github.com/OpenHFT/Chronicle-Salt/releases/chronicle-salt-2.17.2), [BOM-2.17.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Salt-2.17.2](https://github.com/OpenHFT/Chronicle-Salt/releases/chronicle-salt-2.17.2), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)
