### ISSUE TITLE
Support Apple Silicon

### ISSUE THREAD

**Issue by maxim-ponomarev** [OpenHFT/Chronicle-Salt#27]
On macOS, since release of Apple Silicon, Homebrew installs libraries built for Apple Silicon to `/opt/homebrew/lib`, instead of `/usr/local/lib` (which is now supposed to contain binaries for Rosetta 2).

Let's add `/opt/homebrew/lib` to the list of possible `libsodium` locations, so it won't require any manual changes for users of Chronicle-Salt on Apple Silicon based computers.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Salt-2.23ea4](https://github.com/OpenHFT/Chronicle-Salt/releases/chronicle-salt-2.23ea4), [BOM-2.23ea121](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea121)
